name: 'Composite Xcode Path'
description: 'Get Xcode version to be used across all actions'
outputs:
  xcode-path:
    description: "Path to current Xcode version"
    value: ${{ steps.xcode-path.outputs.xcode-path }}
runs:
  using: "composite"
  steps:
    - name: Set XCODE_PATH env var
      env:
        XCODE_PATH: "/Applications/Xcode.app"
      run: echo "XCODE_PATH=${{ env.XCODE_PATH }}" >> $GITHUB_ENV
      shell: bash
    - name: Set Xcode version
      run: sudo xcode-select -s ${{ env.XCODE_PATH }}
      shell: bash
    - name: Output Xcode path
      id: xcode-path
      run: echo "::set-output name=xcode-path::$(echo ${{ env.XCODE_PATH }})"
      shell: bash